apiVersion: ""
kind: ""
logging:
  level: info
  sinks:
    - json: true
      path: gcplogs:///projects/fred-dev/logs/foyle
    - json: false
      path: stderr
server:
  bindAddress: 0.0.0.0
  httpMaxReadTimeout: 1m0s
  httpMaxWriteTimeout: 1m0s
  cors:

agent:
  model: claude-3-5-sonnet-20240620
  modelProvider: anthropic
  rag:
    enabled: true
    maxResults: 3
  evalMode: false
openai:
  apiKeyFile: /Users/red/secrets/openapi.api.key
  baseURL: ""
telemetry:
  honeycomb:
    apiKeyFile: /Users/fred/secrets/honeycomb.api.key
learner:
  logDirs: []
  exampleDirs:
    - /Users/fred/.foyle/training
