# Release foyle resources
# https://github.com/jlewi/hydros/blob/main/docs/continuous_delivery.md
#
# A repoconfig will apply all the hydros resources that much the selector
apiVersion: hydros.dev/v1alpha1
kind: RepoConfig
metadata:
  name: foyle
  namespace: foyle
spec:
  # TODO(jeremy): Update this to main after testing it out.
  repo: https://github.com/jlewi/foyle.git?ref=jlewi/releasing
  globs:
    - "**/*.yaml"
  selectors:
    - matchLabels:
        env: release
