# Release foyle resources
# https://github.com/jlewi/hydros/blob/main/docs/continuous_delivery.md
apiVersion: hydros.dev/v1alpha1
kind: RepoConfig
metadata:
  name: foyle
  namespace: foyle
spec:
  repo: https://github.com/jlewi/foyle.git
  gitHubAppConfig:
    appID: 315982
    privateKey: gcpsecretmanager:///projects/foyle-dev/secrets/foyle-ghapp-key/versions/latest
  globs:
    - "**/*.yaml"
  selectors:
    - matchLabels:
        env: release