package logsviewer

import (
	"bytes"
	"github.com/go-logr/zapr"
	"github.com/jlewi/foyle/app/pkg/analyze"
	"github.com/pkg/errors"
	"github.com/yuin/goldmark"
	"go.uber.org/zap"
)

// renderGeneratedBlock returns the generated block as HTML if there is one
func renderGeneratedBlock(block *analyze.BlockLog) (string, error) {
	if block == nil {
		return "", errors.New("block is nil")
	}
	log := zapr.NewLogger(zap.L())

	if block.GeneratedBlock == nil {
		return "Block was not generated by the assistant", nil
	}

	var buf bytes.Buffer
	if err := goldmark.Convert([]byte(block.GeneratedBlock.Contents), &buf); err != nil {
		log.Error(err, "Failed to convert markdown")
		return "", err
	}

	return string(buf.Bytes()), nil
}

// renderExecutedBlock returns the executed block as HTML if there is one
func renderExecutedBlock(block *analyze.BlockLog) (string, error) {
	if block == nil {
		return "", errors.New("block is nil")
	}
	log := zapr.NewLogger(zap.L())

	if block.ExecutedBlock == nil {
		return "Block was not executed", nil
	}

	var buf bytes.Buffer
	if err := goldmark.Convert([]byte(block.ExecutedBlock.Contents), &buf); err != nil {
		log.Error(err, "Failed to convert markdown")
		return "", err
	}

	return string(buf.Bytes()), nil
}
