// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: foyle/logs/logs.proto

package logspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogsWaterMark is the watermark keep track of the logs that have been processed
type LogsWaterMark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The file is the name of the file that is associated with the watermark
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// The offset is the offset in the file that is associated with the watermark
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *LogsWaterMark) Reset() {
	*x = LogsWaterMark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foyle_logs_logs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogsWaterMark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsWaterMark) ProtoMessage() {}

func (x *LogsWaterMark) ProtoReflect() protoreflect.Message {
	mi := &file_foyle_logs_logs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsWaterMark.ProtoReflect.Descriptor instead.
func (*LogsWaterMark) Descriptor() ([]byte, []int) {
	return file_foyle_logs_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogsWaterMark) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LogsWaterMark) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLogsStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLogsStatusRequest) Reset() {
	*x = GetLogsStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foyle_logs_logs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLogsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsStatusRequest) ProtoMessage() {}

func (x *GetLogsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foyle_logs_logs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsStatusRequest.ProtoReflect.Descriptor instead.
func (*GetLogsStatusRequest) Descriptor() ([]byte, []int) {
	return file_foyle_logs_logs_proto_rawDescGZIP(), []int{1}
}

type GetLogsStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watermark *LogsWaterMark `protobuf:"bytes,1,opt,name=watermark,proto3" json:"watermark,omitempty"`
}

func (x *GetLogsStatusResponse) Reset() {
	*x = GetLogsStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foyle_logs_logs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLogsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsStatusResponse) ProtoMessage() {}

func (x *GetLogsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foyle_logs_logs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsStatusResponse.ProtoReflect.Descriptor instead.
func (*GetLogsStatusResponse) Descriptor() ([]byte, []int) {
	return file_foyle_logs_logs_proto_rawDescGZIP(), []int{2}
}

func (x *GetLogsStatusResponse) GetWatermark() *LogsWaterMark {
	if x != nil {
		return x.Watermark
	}
	return nil
}

var File_foyle_logs_logs_proto protoreflect.FileDescriptor

var file_foyle_logs_logs_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x67,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2e, 0x6c,
	0x6f, 0x67, 0x73, 0x22, 0x3b, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x73, 0x57, 0x61, 0x74, 0x65, 0x72,
	0x4d, 0x61, 0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c,
	0x6f, 0x67, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2e, 0x6c, 0x6f, 0x67,
	0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x57, 0x61, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x72, 0x6b, 0x52,
	0x09, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x42, 0x98, 0x01, 0x0a, 0x0e, 0x63,
	0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x42, 0x09, 0x4c,
	0x6f, 0x67, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6c, 0x65, 0x77, 0x69, 0x2f, 0x66, 0x6f, 0x79,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x66, 0x6f, 0x79,
	0x6c, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x3b, 0x6c, 0x6f, 0x67, 0x73, 0x70, 0x62, 0xa2, 0x02,
	0x03, 0x46, 0x4c, 0x58, 0xaa, 0x02, 0x0a, 0x46, 0x6f, 0x79, 0x6c, 0x65, 0x2e, 0x4c, 0x6f, 0x67,
	0x73, 0xca, 0x02, 0x0a, 0x46, 0x6f, 0x79, 0x6c, 0x65, 0x5c, 0x4c, 0x6f, 0x67, 0x73, 0xe2, 0x02,
	0x16, 0x46, 0x6f, 0x79, 0x6c, 0x65, 0x5c, 0x4c, 0x6f, 0x67, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x46, 0x6f, 0x79, 0x6c, 0x65, 0x3a,
	0x3a, 0x4c, 0x6f, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foyle_logs_logs_proto_rawDescOnce sync.Once
	file_foyle_logs_logs_proto_rawDescData = file_foyle_logs_logs_proto_rawDesc
)

func file_foyle_logs_logs_proto_rawDescGZIP() []byte {
	file_foyle_logs_logs_proto_rawDescOnce.Do(func() {
		file_foyle_logs_logs_proto_rawDescData = protoimpl.X.CompressGZIP(file_foyle_logs_logs_proto_rawDescData)
	})
	return file_foyle_logs_logs_proto_rawDescData
}

var file_foyle_logs_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_foyle_logs_logs_proto_goTypes = []interface{}{
	(*LogsWaterMark)(nil),         // 0: foyle.logs.LogsWaterMark
	(*GetLogsStatusRequest)(nil),  // 1: foyle.logs.GetLogsStatusRequest
	(*GetLogsStatusResponse)(nil), // 2: foyle.logs.GetLogsStatusResponse
}
var file_foyle_logs_logs_proto_depIdxs = []int32{
	0, // 0: foyle.logs.GetLogsStatusResponse.watermark:type_name -> foyle.logs.LogsWaterMark
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_foyle_logs_logs_proto_init() }
func file_foyle_logs_logs_proto_init() {
	if File_foyle_logs_logs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foyle_logs_logs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogsWaterMark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foyle_logs_logs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLogsStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foyle_logs_logs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLogsStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foyle_logs_logs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foyle_logs_logs_proto_goTypes,
		DependencyIndexes: file_foyle_logs_logs_proto_depIdxs,
		MessageInfos:      file_foyle_logs_logs_proto_msgTypes,
	}.Build()
	File_foyle_logs_logs_proto = out.File
	file_foyle_logs_logs_proto_rawDesc = nil
	file_foyle_logs_logs_proto_goTypes = nil
	file_foyle_logs_logs_proto_depIdxs = nil
}
