// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: foyle/logs/traces.proto

package logs

import (
	v1alpha1 "github.com/jlewi/foyle/protos/go/foyle/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Types that are assignable to Data:
	//	*Trace_Generate
	//	*Trace_Execute
	Data isTrace_Data `protobuf_oneof:"data"`
}

func (x *Trace) Reset() {
	*x = Trace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foyle_logs_traces_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_foyle_logs_traces_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_foyle_logs_traces_proto_rawDescGZIP(), []int{0}
}

func (x *Trace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trace) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Trace) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (m *Trace) GetData() isTrace_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Trace) GetGenerate() *GenerateTrace {
	if x, ok := x.GetData().(*Trace_Generate); ok {
		return x.Generate
	}
	return nil
}

func (x *Trace) GetExecute() *ExecuteTrace {
	if x, ok := x.GetData().(*Trace_Execute); ok {
		return x.Execute
	}
	return nil
}

type isTrace_Data interface {
	isTrace_Data()
}

type Trace_Generate struct {
	Generate *GenerateTrace `protobuf:"bytes,4,opt,name=generate,proto3,oneof"`
}

type Trace_Execute struct {
	Execute *ExecuteTrace `protobuf:"bytes,5,opt,name=execute,proto3,oneof"`
}

func (*Trace_Generate) isTrace_Data() {}

func (*Trace_Execute) isTrace_Data() {}

type GenerateTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *v1alpha1.GenerateRequest  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response *v1alpha1.GenerateResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *GenerateTrace) Reset() {
	*x = GenerateTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foyle_logs_traces_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTrace) ProtoMessage() {}

func (x *GenerateTrace) ProtoReflect() protoreflect.Message {
	mi := &file_foyle_logs_traces_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTrace.ProtoReflect.Descriptor instead.
func (*GenerateTrace) Descriptor() ([]byte, []int) {
	return file_foyle_logs_traces_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTrace) GetRequest() *v1alpha1.GenerateRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GenerateTrace) GetResponse() *v1alpha1.GenerateResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ExecuteTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *v1alpha1.ExecuteRequest  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response *v1alpha1.ExecuteResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ExecuteTrace) Reset() {
	*x = ExecuteTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foyle_logs_traces_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTrace) ProtoMessage() {}

func (x *ExecuteTrace) ProtoReflect() protoreflect.Message {
	mi := &file_foyle_logs_traces_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTrace.ProtoReflect.Descriptor instead.
func (*ExecuteTrace) Descriptor() ([]byte, []int) {
	return file_foyle_logs_traces_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteTrace) GetRequest() *v1alpha1.ExecuteRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecuteTrace) GetResponse() *v1alpha1.ExecuteResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_foyle_logs_traces_proto protoreflect.FileDescriptor

var file_foyle_logs_traces_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x66, 0x6f, 0x79, 0x6c, 0x65,
	0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x01, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x2c, 0x0a, 0x08, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x48, 0x00, 0x52, 0x08, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x29,
	0x0a, 0x07, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x65, 0x48, 0x00,
	0x52, 0x07, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x6a, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x67, 0x0a,
	0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x29, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6c, 0x65, 0x77, 0x69, 0x2f, 0x66, 0x6f, 0x79, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x66, 0x6f, 0x79, 0x6c, 0x65,
	0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foyle_logs_traces_proto_rawDescOnce sync.Once
	file_foyle_logs_traces_proto_rawDescData = file_foyle_logs_traces_proto_rawDesc
)

func file_foyle_logs_traces_proto_rawDescGZIP() []byte {
	file_foyle_logs_traces_proto_rawDescOnce.Do(func() {
		file_foyle_logs_traces_proto_rawDescData = protoimpl.X.CompressGZIP(file_foyle_logs_traces_proto_rawDescData)
	})
	return file_foyle_logs_traces_proto_rawDescData
}

var file_foyle_logs_traces_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_foyle_logs_traces_proto_goTypes = []interface{}{
	(*Trace)(nil),                     // 0: Trace
	(*GenerateTrace)(nil),             // 1: GenerateTrace
	(*ExecuteTrace)(nil),              // 2: ExecuteTrace
	(*timestamppb.Timestamp)(nil),     // 3: google.protobuf.Timestamp
	(*v1alpha1.GenerateRequest)(nil),  // 4: GenerateRequest
	(*v1alpha1.GenerateResponse)(nil), // 5: GenerateResponse
	(*v1alpha1.ExecuteRequest)(nil),   // 6: ExecuteRequest
	(*v1alpha1.ExecuteResponse)(nil),  // 7: ExecuteResponse
}
var file_foyle_logs_traces_proto_depIdxs = []int32{
	3, // 0: Trace.start_time:type_name -> google.protobuf.Timestamp
	3, // 1: Trace.end_time:type_name -> google.protobuf.Timestamp
	1, // 2: Trace.generate:type_name -> GenerateTrace
	2, // 3: Trace.execute:type_name -> ExecuteTrace
	4, // 4: GenerateTrace.request:type_name -> GenerateRequest
	5, // 5: GenerateTrace.response:type_name -> GenerateResponse
	6, // 6: ExecuteTrace.request:type_name -> ExecuteRequest
	7, // 7: ExecuteTrace.response:type_name -> ExecuteResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_foyle_logs_traces_proto_init() }
func file_foyle_logs_traces_proto_init() {
	if File_foyle_logs_traces_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foyle_logs_traces_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foyle_logs_traces_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foyle_logs_traces_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_foyle_logs_traces_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Trace_Generate)(nil),
		(*Trace_Execute)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foyle_logs_traces_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foyle_logs_traces_proto_goTypes,
		DependencyIndexes: file_foyle_logs_traces_proto_depIdxs,
		MessageInfos:      file_foyle_logs_traces_proto_msgTypes,
	}.Build()
	File_foyle_logs_traces_proto = out.File
	file_foyle_logs_traces_proto_rawDesc = nil
	file_foyle_logs_traces_proto_goTypes = nil
	file_foyle_logs_traces_proto_depIdxs = nil
}
