// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: foyle/v1alpha1/providers.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelProvider int32

const (
	ModelProvider_MODEL_PROVIDER_UNKNOWN ModelProvider = 0
	ModelProvider_OPEN_AI                ModelProvider = 1
	ModelProvider_ANTHROPIC              ModelProvider = 2
	ModelProvider_REPLICATE              ModelProvider = 3
)

// Enum value maps for ModelProvider.
var (
	ModelProvider_name = map[int32]string{
		0: "MODEL_PROVIDER_UNKNOWN",
		1: "OPEN_AI",
		2: "ANTHROPIC",
		3: "REPLICATE",
	}
	ModelProvider_value = map[string]int32{
		"MODEL_PROVIDER_UNKNOWN": 0,
		"OPEN_AI":                1,
		"ANTHROPIC":              2,
		"REPLICATE":              3,
	}
)

func (x ModelProvider) Enum() *ModelProvider {
	p := new(ModelProvider)
	*p = x
	return p
}

func (x ModelProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_foyle_v1alpha1_providers_proto_enumTypes[0].Descriptor()
}

func (ModelProvider) Type() protoreflect.EnumType {
	return &file_foyle_v1alpha1_providers_proto_enumTypes[0]
}

func (x ModelProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelProvider.Descriptor instead.
func (ModelProvider) EnumDescriptor() ([]byte, []int) {
	return file_foyle_v1alpha1_providers_proto_rawDescGZIP(), []int{0}
}

var File_foyle_v1alpha1_providers_proto protoreflect.FileDescriptor

var file_foyle_v1alpha1_providers_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2a, 0x56, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49,
	0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x41, 0x49, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4e,
	0x54, 0x48, 0x52, 0x4f, 0x50, 0x49, 0x43, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x50,
	0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x10, 0x03, 0x42, 0x43, 0x42, 0x0e, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6c, 0x65, 0x77, 0x69, 0x2f, 0x66,
	0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x66,
	0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foyle_v1alpha1_providers_proto_rawDescOnce sync.Once
	file_foyle_v1alpha1_providers_proto_rawDescData = file_foyle_v1alpha1_providers_proto_rawDesc
)

func file_foyle_v1alpha1_providers_proto_rawDescGZIP() []byte {
	file_foyle_v1alpha1_providers_proto_rawDescOnce.Do(func() {
		file_foyle_v1alpha1_providers_proto_rawDescData = protoimpl.X.CompressGZIP(file_foyle_v1alpha1_providers_proto_rawDescData)
	})
	return file_foyle_v1alpha1_providers_proto_rawDescData
}

var file_foyle_v1alpha1_providers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_foyle_v1alpha1_providers_proto_goTypes = []any{
	(ModelProvider)(0), // 0: ModelProvider
}
var file_foyle_v1alpha1_providers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foyle_v1alpha1_providers_proto_init() }
func file_foyle_v1alpha1_providers_proto_init() {
	if File_foyle_v1alpha1_providers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foyle_v1alpha1_providers_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foyle_v1alpha1_providers_proto_goTypes,
		DependencyIndexes: file_foyle_v1alpha1_providers_proto_depIdxs,
		EnumInfos:         file_foyle_v1alpha1_providers_proto_enumTypes,
	}.Build()
	File_foyle_v1alpha1_providers_proto = out.File
	file_foyle_v1alpha1_providers_proto_rawDesc = nil
	file_foyle_v1alpha1_providers_proto_goTypes = nil
	file_foyle_v1alpha1_providers_proto_depIdxs = nil
}
