// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: foyle/v1alpha1/trainer.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Example represents an example to be used in few shot learning
// It is also used to represent examples during evaluation.
type Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Embedding []float32 `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Query     *Doc      `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Answer    []*Block  `protobuf:"bytes,4,rep,name=answer,proto3" json:"answer,omitempty"`
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_foyle_v1alpha1_trainer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_foyle_v1alpha1_trainer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_foyle_v1alpha1_trainer_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Example) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *Example) GetQuery() *Doc {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Example) GetAnswer() []*Block {
	if x != nil {
		return x.Answer
	}
	return nil
}

type RAGResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Example *Example `protobuf:"bytes,1,opt,name=example,proto3" json:"example,omitempty"`
	Score   float64  `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *RAGResult) Reset() {
	*x = RAGResult{}
	mi := &file_foyle_v1alpha1_trainer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGResult) ProtoMessage() {}

func (x *RAGResult) ProtoReflect() protoreflect.Message {
	mi := &file_foyle_v1alpha1_trainer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGResult.ProtoReflect.Descriptor instead.
func (*RAGResult) Descriptor() ([]byte, []int) {
	return file_foyle_v1alpha1_trainer_proto_rawDescGZIP(), []int{1}
}

func (x *RAGResult) GetExample() *Example {
	if x != nil {
		return x.Example
	}
	return nil
}

func (x *RAGResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_foyle_v1alpha1_trainer_proto protoreflect.FileDescriptor

var file_foyle_v1alpha1_trainer_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18,
	0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x64,
	0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x07, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x1a, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04,
	0x2e, 0x44, 0x6f, 0x63, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x06, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x09, 0x52,
	0x41, 0x47, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x45, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x52, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x42, 0x41, 0x42, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6a, 0x6c, 0x65, 0x77, 0x69, 0x2f, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x66, 0x6f, 0x79, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foyle_v1alpha1_trainer_proto_rawDescOnce sync.Once
	file_foyle_v1alpha1_trainer_proto_rawDescData = file_foyle_v1alpha1_trainer_proto_rawDesc
)

func file_foyle_v1alpha1_trainer_proto_rawDescGZIP() []byte {
	file_foyle_v1alpha1_trainer_proto_rawDescOnce.Do(func() {
		file_foyle_v1alpha1_trainer_proto_rawDescData = protoimpl.X.CompressGZIP(file_foyle_v1alpha1_trainer_proto_rawDescData)
	})
	return file_foyle_v1alpha1_trainer_proto_rawDescData
}

var file_foyle_v1alpha1_trainer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_foyle_v1alpha1_trainer_proto_goTypes = []any{
	(*Example)(nil),   // 0: Example
	(*RAGResult)(nil), // 1: RAGResult
	(*Doc)(nil),       // 2: Doc
	(*Block)(nil),     // 3: Block
}
var file_foyle_v1alpha1_trainer_proto_depIdxs = []int32{
	2, // 0: Example.query:type_name -> Doc
	3, // 1: Example.answer:type_name -> Block
	0, // 2: RAGResult.example:type_name -> Example
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_foyle_v1alpha1_trainer_proto_init() }
func file_foyle_v1alpha1_trainer_proto_init() {
	if File_foyle_v1alpha1_trainer_proto != nil {
		return
	}
	file_foyle_v1alpha1_doc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foyle_v1alpha1_trainer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foyle_v1alpha1_trainer_proto_goTypes,
		DependencyIndexes: file_foyle_v1alpha1_trainer_proto_depIdxs,
		MessageInfos:      file_foyle_v1alpha1_trainer_proto_msgTypes,
	}.Build()
	File_foyle_v1alpha1_trainer_proto = out.File
	file_foyle_v1alpha1_trainer_proto_rawDesc = nil
	file_foyle_v1alpha1_trainer_proto_goTypes = nil
	file_foyle_v1alpha1_trainer_proto_depIdxs = nil
}
