apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml

configMapGenerator:
  - name: foyle-config    
    files:
      - foyle.yaml
commonLabels:
  app: foyle  
namespace: foyle
