// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package fsql

import (
	"database/sql"
)

type Session struct {
	Contextid sql.NullString
	Starttime sql.NullTime
	Endtime   sql.NullTime
	Proto     []byte
}
